let passagerEnModification=null;
function afficherPassagers(liste=TT.passagers){const body=document.getElementById("passagersBody");if(!body)return;body.innerHTML=liste.length?liste.map(p=>`<tr><td><strong>${escapeHTML(p.id)}</strong></td><td>${escapeHTML(p.nom)}</td><td>${escapeHTML(p.prenom)}</td><td>${escapeHTML(p.telephone)}</td><td>${escapeHTML(p.email)}</td><td>${escapeHTML(p.pieceIdentite)}</td><td class="actions"><button class="btn btn-outline btn-small" onclick="modifierPassager('${p.id}')">Modifier</button><button class="btn btn-danger btn-small" onclick="supprimerPassager('${p.id}')">Supprimer</button></td></tr>`).join(""):`<tr><td colspan="7" class="empty">Aucun passager.</td></tr>`;}
function validerFormulairePassager(){
  const nom=document.getElementById("passagerNom").value.trim(),prenom=document.getElementById("passagerPrenom").value.trim(),tel=document.getElementById("passagerTelephone").value.replace(/\s+/g,"").trim(),email=document.getElementById("passagerEmail").value.trim(),piece=document.getElementById("passagerPiece").value;
  let ok=true; const lettres=/^[A-Za-zÀ-ÖØ-öø-ÿ' -]{2,}$/; const senegal=/^(77|78)\d{7}$/; const mail=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  ["errId","errNom","errPrenom","errTelephone","errEmail","errPiece"].forEach(id=>afficherErreur(id,""));
  const id=document.getElementById("passagerId").value.trim().toUpperCase();
  if(!/^P\d{3,}$/.test(id)){afficherErreur("errId","Format attendu : P011.");ok=false;}
  if(!lettres.test(nom)){afficherErreur("errNom","Au moins 2 lettres et espaces uniquement.");ok=false;}
  if(!lettres.test(prenom)){afficherErreur("errPrenom","Au moins 2 lettres et espaces uniquement.");ok=false;}
  if(!senegal.test(tel)){afficherErreur("errTelephone","Numéro sénégalais valide : 77xxxxxxx ou 78xxxxxxx (9 chiffres). Vous pouvez écrire des espaces.");ok=false;}
  if(!mail.test(email)){afficherErreur("errEmail","Adresse e-mail invalide.");ok=false;}
  if(!piece){afficherErreur("errPiece","Choisissez une pièce d'identité.");ok=false;}
  return ok;
}
function ajouterModifierSupprimerPassager(){if(!validerFormulairePassager())return;const id=document.getElementById("passagerId").value.trim().toUpperCase();if(!passagerEnModification&&TT.passagers.some(p=>p.id===id))return afficherErreur("errId","Cet ID existe déjà.");const p={id,nom:document.getElementById("passagerNom").value.trim(),prenom:document.getElementById("passagerPrenom").value.trim(),telephone:document.getElementById("passagerTelephone").value.replace(/\s+/g,""),email:document.getElementById("passagerEmail").value.trim(),pieceIdentite:document.getElementById("passagerPiece").value};if(passagerEnModification){const i=TT.passagers.findIndex(x=>x.id===passagerEnModification);if(i<0)return;TT.passagers[i]=p;}else TT.passagers.push(p);sauvegarderDonnees();afficherPassagers();resetFormPassager();document.getElementById("passagerMessage").textContent="Passager enregistré et stocké localement.";}
function modifierPassager(id){const p=trouverPassager(id);if(!p)return;passagerEnModification=id;document.getElementById("passagerId").value=p.id;document.getElementById("passagerNom").value=p.nom;document.getElementById("passagerPrenom").value=p.prenom;document.getElementById("passagerTelephone").value=p.telephone;document.getElementById("passagerEmail").value=p.email;document.getElementById("passagerPiece").value=p.pieceIdentite;document.getElementById("passagerSubmit").textContent="Enregistrer les modifications";document.getElementById("passagerCancel").classList.remove("hidden");document.getElementById("passagerForm").scrollIntoView({behavior:"smooth"});}
function supprimerPassager(id){if(TT.reservations.some(r=>r.passagerId===id&&r.statut==="Confirmee"))return alert("Impossible : ce passager possède une réservation confirmée.");if(!confirm(`Supprimer le passager ${id} ?`))return;TT.passagers=TT.passagers.filter(p=>p.id!==id);sauvegarderDonnees();afficherPassagers();}
function resetFormPassager(){document.getElementById("passagerForm")?.reset();passagerEnModification=null;document.getElementById("passagerSubmit").textContent="Ajouter le passager";document.getElementById("passagerCancel").classList.add("hidden");["errId","errNom","errPrenom","errTelephone","errEmail","errPiece"].forEach(id=>afficherErreur(id,""));}
function rechercherPassager(mot){const q=String(mot||"").toLowerCase().replace(/\s/g,"");const liste=TT.passagers.filter(p=>[p.id,p.nom,p.prenom,p.telephone].some(v=>String(v).toLowerCase().replace(/\s/g,"").includes(q)));afficherPassagers(liste);}
document.addEventListener("DOMContentLoaded",async()=>{if(!document.getElementById("passagersBody"))return;await initialiserDonnees();afficherPassagers();document.getElementById("recherchePassager")?.addEventListener("input",e=>rechercherPassager(e.target.value));document.getElementById("passagerForm")?.addEventListener("submit",e=>{e.preventDefault();ajouterModifierSupprimerPassager();});document.getElementById("passagerCancel")?.addEventListener("click",resetFormPassager);document.getElementById("resetData")?.addEventListener("click",reinitialiserDonneesXML);});
