function calculerTauxRemplissage(carId){const car=trouverCar(carId);if(!car)return 0;const trajets=TT.trajets.filter(t=>t.carId===carId);const capacite=trajets.reduce((s,t)=>s+car.placesTotal,0);const reservees=TT.reservations.filter(r=>r.statut==="Confirmee"&&trajets.some(t=>t.id===r.trajetId)).length;return capacite?Math.min(100,(reservees/capacite)*100):0;}
function afficherStatistiques(){
  document.getElementById("totalCars").textContent=TT.cars.length;document.getElementById("totalTrajets").textContent=TT.trajets.length;document.getElementById("totalPassagers").textContent=TT.passagers.length;document.getElementById("totalReservations").textContent=TT.reservations.length;
  const conf=TT.reservations.filter(r=>r.statut==="Confirmee").length,ann=TT.reservations.filter(r=>r.statut==="Annulee").length;document.getElementById("reservationsConfirmees").textContent=conf;document.getElementById("reservationsAnnulees").textContent=ann;
  document.getElementById("remplissageCars").innerHTML=TT.cars.length?TT.cars.map(c=>{const rate=calculerTauxRemplissage(c.id);return `<div class="progress-row"><div class="progress-label"><strong>${escapeHTML(c.id)} — ${escapeHTML(c.marque)} ${escapeHTML(c.modele)}</strong><span>${rate.toFixed(1)} %</span></div><div class="progress"><div class="progress-bar" style="width:${rate}%"></div></div></div>`}).join(""):"Aucun car.";
  const months={};TT.reservations.filter(r=>r.statut==="Confirmee").forEach(r=>{const m=r.dateReservation.slice(0,7);months[m]=(months[m]||0)+r.prix;});const mb=document.getElementById("revenusMensuelsBody");mb.innerHTML=Object.keys(months).sort().map(m=>`<tr><td>${new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(new Date(m+"-01"))}</td><td><strong>${formatFCFA(months[m])}</strong></td></tr>`).join("")||`<tr><td colspan="2">Aucun revenu.</td></tr>`;
  const rb=document.getElementById("revenusTrajetsBody");rb.innerHTML=TT.trajets.map(t=>{const list=TT.reservations.filter(r=>r.trajetId===t.id&&r.statut==="Confirmee");return `<tr><td>${escapeHTML(t.id)}</td><td>${escapeHTML(t.villeArrivee)}</td><td>${t.date}</td><td>${list.length}</td><td><strong>${formatFCFA(list.reduce((s,r)=>s+r.prix,0))}</strong></td></tr>`}).join("")||`<tr><td colspan="5">Aucun trajet.</td></tr>`;
}
document.addEventListener("DOMContentLoaded",async()=>{if(!document.getElementById("totalCars"))return;await initialiserDonnees();afficherStatistiques();document.getElementById("resetData")?.addEventListener("click",reinitialiserDonneesXML);});
