let placeSelectionnee=null;
function remplirSelectReservations(){
  const p=document.getElementById("reservationPassager"),t=document.getElementById("reservationTrajet");
  if(p)p.innerHTML=`<option value="">Choisir un passager</option>`+TT.passagers.map(x=>`<option value="${x.id}">${escapeHTML(x.id)} — ${escapeHTML(x.prenom)} ${escapeHTML(x.nom)} — ${escapeHTML(x.telephone)}</option>`).join("");
  if(t)t.innerHTML=`<option value="">Choisir un trajet</option>`+TT.trajets.map(x=>{const c=trouverCar(x.carId);return `<option value="${x.id}">${escapeHTML(x.id)} — ${escapeHTML(x.villeDepart)} → ${escapeHTML(x.villeArrivee)} — ${x.date} ${x.heureDepart} — ${x.placesDisponibles} places</option>`}).join("");
}
function reservationsConfirmeesDuTrajet(id){return TT.reservations.filter(r=>r.trajetId===id&&r.statut==="Confirmee");}
function verifierDisponibilitePlace(trajetId,place){const t=trouverTrajet(trajetId),c=t&&trouverCar(t.carId);if(!t||!c||place<1||place>c.placesTotal)return false;return !reservationsConfirmeesDuTrajet(trajetId).some(r=>r.place===place);}
function afficherPlacesCar(trajetId){
  const grid=document.getElementById("seatGrid"),info=document.getElementById("seatInfo"),status=document.getElementById("seatStatus");placeSelectionnee=null;document.getElementById("reservationPlace").value="";afficherErreur("errReservationPlace","");
  if(!grid)return;const t=trouverTrajet(trajetId);if(!t){grid.innerHTML="";info.textContent="Sélectionnez un trajet.";if(status)status.innerHTML="";return;}const c=trouverCar(t.carId);if(!c){grid.innerHTML="";return;}
  const reserves=new Set(reservationsConfirmeesDuTrajet(trajetId).map(r=>r.place)); info.textContent=`${t.villeDepart} → ${t.villeArrivee} | ${t.date} ${t.heureDepart} | ${t.placesDisponibles} place(s) disponible(s)`; if(status)status.innerHTML=statutBadge("Confirmee")+" <small>Statut appliqué à toute nouvelle réservation</small>";
  grid.innerHTML=Array.from({length:c.placesTotal},(_,i)=>{const n=i+1,occ=reserves.has(n);return `<button type="button" class="seat ${occ?"reserved":"free"}" ${occ?"disabled":""} aria-label="Place ${n} ${occ?"réservée":"disponible"}" onclick="selectionnerPlace(${n})">${n}</button>`}).join("");
}
function selectionnerPlace(place){const trajetId=document.getElementById("reservationTrajet").value;if(!verifierDisponibilitePlace(trajetId,place)){afficherErreur("errReservationPlace","Cette place est déjà réservée.");return;}placeSelectionnee=place;document.getElementById("reservationPlace").value=place;afficherErreur("errReservationPlace","");document.querySelectorAll(".seat").forEach(b=>b.classList.toggle("selected",Number(b.textContent)===place));}
function validerFormulaireReservation(){let ok=true;const p=document.getElementById("reservationPassager").value,t=document.getElementById("reservationTrajet").value;["errReservationPassager","errReservationTrajet","errReservationPlace"].forEach(x=>afficherErreur(x,""));if(!p){afficherErreur("errReservationPassager","Choisissez un passager existant.");ok=false;}if(!t){afficherErreur("errReservationTrajet","Choisissez un trajet existant.");ok=false;}if(t&&!placeSelectionnee){afficherErreur("errReservationPlace","Choisissez une place disponible.");ok=false;}if(t&&placeSelectionnee&&!verifierDisponibilitePlace(t,placeSelectionnee)){afficherErreur("errReservationPlace","Cette place vient d'être réservée. Choisissez-en une autre.");ok=false;}return ok;}
function effectuerReservation(passagerId,trajetId,place){if(!verifierDisponibilitePlace(trajetId,place))return false;const t=trouverTrajet(trajetId);const r={id:genererIdReservation(),passagerId,trajetId,place,dateReservation:aujourdHuiISO(),prix:t.prix,statut:"Confirmee"};TT.reservations.push(r);mettreAJourPlacesDisponibles(trajetId);sauvegarderDonnees();return true;}
function genererIdReservation(){let n=TT.reservations.reduce((m,r)=>Math.max(m,Number(String(r.id).replace(/\D/g,""))||0),0)+1;let id=`R${String(n).padStart(3,"0")}`;while(TT.reservations.some(r=>r.id===id)){n++;id=`R${String(n).padStart(3,"0")}`;}return id;}
function annulerReservation(id){const r=trouverReservation(id);if(!r||r.statut==="Annulee")return;if(!confirm(`Annuler la réservation ${id} ?`))return;r.statut="Annulee";mettreAJourPlacesDisponibles(r.trajetId);sauvegarderDonnees();afficherReservations();remplirSelectReservations();if(document.getElementById("reservationTrajet").value)afficherPlacesCar(document.getElementById("reservationTrajet").value);}
function afficherReservations(liste=TT.reservations){const body=document.getElementById("reservationsBody");if(!body)return;body.innerHTML=liste.length?liste.map(r=>{const p=trouverPassager(r.passagerId),t=trouverTrajet(r.trajetId),c=t&&trouverCar(t.carId);return `<tr><td><strong>${r.id}</strong></td><td>${p?escapeHTML(p.prenom+" "+p.nom):r.passagerId}</td><td>${t?escapeHTML(t.villeDepart+" → "+t.villeArrivee):r.trajetId}</td><td>${r.trajetId}</td><td>${c?escapeHTML(c.id):"—"}</td><td>${r.place}</td><td>${r.dateReservation}</td><td>${formatFCFA(r.prix)}</td><td>${statutBadge(r.statut)}</td><td>${r.statut==="Confirmee"?`<button class="btn btn-danger btn-small" onclick="annulerReservation('${r.id}')">Annuler</button>`:`<span class="text-muted">Libérée</span>`}</td></tr>`}).join(""):`<tr><td colspan="10" class="empty">Aucune réservation.</td></tr>`;}
function filtrerReservations(criteres={}){const q=String(criteres.destination||"").toLowerCase();const date=criteres.date||"",status=criteres.statut||"",car=String(criteres.car||"").toLowerCase();const list=TT.reservations.filter(r=>{const t=trouverTrajet(r.trajetId),c=t&&trouverCar(t.carId);return (!date||r.dateReservation===date)&&(!q||(t&&t.villeArrivee.toLowerCase().includes(q)))&&(!status||(status==="confirmee"&&r.statut==="Confirmee")||(status==="annulee"&&r.statut==="Annulee"))&&(!car||(c&&c.id.toLowerCase().includes(car)));});afficherReservations(list);}
document.addEventListener("DOMContentLoaded",async()=>{if(!document.getElementById("reservationsBody"))return;await initialiserDonnees();remplirSelectReservations();afficherReservations();document.getElementById("reservationTrajet")?.addEventListener("change",e=>afficherPlacesCar(e.target.value));document.getElementById("reservationForm")?.addEventListener("submit",e=>{e.preventDefault();if(!validerFormulaireReservation())return;const ok=effectuerReservation(document.getElementById("reservationPassager").value,document.getElementById("reservationTrajet").value,placeSelectionnee);if(ok){document.getElementById("reservationMessage").textContent="Réservation confirmée et stockée localement.";document.getElementById("reservationForm").reset();placeSelectionnee=null;remplirSelectReservations();afficherReservations();afficherPlacesCar(document.getElementById("reservationTrajet").value);}});["filtreDate","filtreDestination","filtreStatut","filtreCar"].forEach(id=>document.getElementById(id)?.addEventListener("input",appliquerFiltres));document.getElementById("resetFiltres")?.addEventListener("click",()=>{["filtreDate","filtreDestination","filtreCar"].forEach(id=>document.getElementById(id).value="");document.getElementById("filtreStatut").value="";afficherReservations();});document.getElementById("resetData")?.addEventListener("click",reinitialiserDonneesXML);});
function appliquerFiltres(){filtrerReservations({date:document.getElementById("filtreDate").value,destination:document.getElementById("filtreDestination").value,statut:document.getElementById("filtreStatut").value,car:document.getElementById("filtreCar").value});}
